version: "1"
services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_DB: "bank"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5433:5432"
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: always
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/bank
      - DB_USERNAME=root
      - DB_PASSWORD=root